language: go

go:
  - 1.10.x

before_install:
  - go get github.com/golang/dep/...
install:
  - $GOPATH/bin/dep ensure
script:
  - env HTTPDOC=1 go test github.com/kutsuzawa/line-reminder/...

addons:
  code_climate:
    repo_token: $CODECLIMATE_COVERAGE_TOKEN
